### ISSUE TITLE
The AudioContext is "suspended". Invoke Tone.start() from a user action to start the audio.

### ISSUE THREAD

**Issue by qunwang6** [ZaneH/metronome#6]
The AudioContext is "suspended". Invoke Tone.start() from a user action to start the audio.

The problem of no sound is occurring on the web.

**Comment by ZaneH** [comment]
> The AudioContext is "suspended". Invoke Tone.start() from a user action to start the audio.
> 
> The problem of no sound is occurring on the web.

I think this happens when you haven't clicked in the window yet. Chrome requires some form of interaction before playing "autoplaying" sounds ([more info here](https://github.com/Tonejs/Tone.js/wiki/Autoplay#problem)).

Let me know if this is still a problem
